'use strict';

teamcheck.controller('checklistCtrl',
	function checklistCtrl($scope) {
		$scope.tasks = [
		{'name':'Cancellation',
		'category':'IPG Daily Morning',
		'task':'IPG Pune',
		'start_time':'10:15 am',
		'end_time':'10:30 am',
		'goal': '10:30 am',
		'sla':'30 min'},
		{'name':'Cancellation',
		'category':'IPG Daily Morning',
		'task':'IPG Pune',
		'start_time':'10:15 am',
		'end_time':'10:30 am',
		'goal': '10:30 am',
		'sla':'30 min'},
		{'name':'Cancellation',
		'category':'IPG Daily Morning',
		'task':'IPG Pune',
		'start_time':'10:15 am',
		'end_time':'10:30 am',
		'goal': '10:30 am',
		'sla':'30 min'},
		{'name':'Cancellation',
		'category':'IPG Daily Morning',
		'task':'IPG Pune',
		'start_time':'10:15 am',
		'end_time':'10:30 am',
		'goal': '10:30 am',
		'sla':'30 min'},
		{'name':'Cancellation',
		'category':'IPG Daily Morning',
		'task':'IPG Pune',
		'start_time':'10:15 am',
		'end_time':'10:30 am',
		'goal': '10:30 am',
		'sla':'30 min'}
		]
		
		$scope.checklists = [
	    {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Nisha',
		 'status': 'active'},
	    {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Nisha',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Nisha',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Rajagopal',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Selwyn',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Nisha',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Nisha',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Wasim',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Selwyn',
		 'status': 'active'},
		 {'name': 'collection checklist',
	     'description': 'Checklist for collections process',
		 'team': 'Collections Pune',
		 'owner': 'Nisha',
		 'status': 'active'}
  ];
			
	}
);	
